### ISSUE TITLE
Fragment Persistence From MainActivity to AnotherActivity

### ISSUE THREAD

**Issue by ersin-ertan** [svenjacobs/android-dagger2-example#1]
Would a singleton FragmentStatePagerAdapter be a good way to retain state across activities, are there any other solutions that you have found?

**Comment by svenjacobs** [comment]
I'm sure there are better solutions. What do you want to achieve?

**Comment by ersin-ertan** [comment]
Instead of creating a new fragment on AnotherActivity, the selected Fragment from MainActivity or at least it's state should carry over. I'm investigating Square/Mortar, which has a persistence implementation for objects.
